### PR TITLE
updated feedstock to version 4.76

### PR DESCRIPTION
**Pull request by xileF1337**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xileF1337** [comment]
@conda-forge-admin, please rerender

**Comment by xileF1337** [comment]
The problem seems to be the fact that file `latexmk.bat` is no longer part of the distribution. It was still present in v4.70b, but vanished in v4.72b. This is not mentioned in the change log. I adapt `bld.bat` ...

**Comment by xileF1337** [comment]
I contacted John Collins, the author of `latexmk`, and he confirmed that `latexmk.bat` is no longer shipped with the distribution. He promised to add `latexmk.cmd` as a replacement for Windows users in the next release, so probably another change to the test command in `meta.yaml` after the next `latexmk` release would be a good thing.

**Comment by xileF1337** [comment]
@conda-forge/staged-recipes please review and merge PR, thank you so much!

**Comment by chrisburr** [comment]
The `staged-recipes` team doesn't have merge rights outside of `staged-recipes`.

You should ping @conda-forge/latexmk to ask for a review. If that team doesn't respond within a few days you can escallated to `@conda-forge/core` (quoted to avoid bothering them prematurely).

You might also want to consider adding yourself to the list mantainers in the `meta.yaml` if your interested. 😄

**Comment by xileF1337** [comment]
Hi Chris,

thanks for your help! 

> You might also want to consider adding yourself to the list mantainers in the meta.yaml if your interested.

That's fine from my side. If @conda-forge/latexmk agrees, I can put my name there ;-)

**Comment by xileF1337** [comment]
Since @conda-forge/latexmk is not responding, I'm kindly asking @conda-forge/core to review and merge this PR.  Thanks for your help!

I was so free to add myself as a maintainer to the yaml file. I hope that's ok, otherwise I can remove myself again.

**Pull request merged**
